### ISSUE TITLE
Deselect "Select all" when not all are selected

### ISSUE THREAD

**Issue by draperunner** [entur/tavla#100]
![image](https://user-images.githubusercontent.com/4339443/65958535-e9593e00-e44f-11e9-8e0c-ecf99035e6ed.png)

On the admin page, the checkbox for "Velg alle" ("Select all") should only and always be checked if all sub-checkmarks also are checked. 

In other words: 
* It should not be possible for the "Velg alle" checkbox to be **checked** if not **all** list items are checked
* It should not be possible for the "Velg alle" checkbox to be **unchecked** if **all** list items are checked.

Steps to reproduce bug:
1. Go to admin page
2. Select "Velg alle"
3. Deselect one of the items in the list

**Comment by DaniloLira** [comment]
I can help you with that

**Comment by draperunner** [comment]
Fixed by #102
