### ISSUE TITLE
Støtte for eldre nettlesere

### ISSUE THREAD

**Issue by forteller** [entur/tavla#1008]
Tavla hadde vært en strålende måte å fortsette å bruke enkelte gamle tableter. Jeg har nettopp kommet over et par iPad 2 som noen hadde kastet, og tenkte at jeg skulle bruke Tavla på dem. Men nei, siden er bare hvit når jeg går inn på tavla.entur.no i denne gamle versjonen av Safari.

For å bidra til mindre e-avfall er det flott om dere fortsetter å støtte eldre nettlesere! Takk!

**Comment by ydalir** [comment]
Heisann, takk for tilbakemeldingen! Vi beklager at Tavla ikke støttes på din enhet. Dette har vi også fått tilbakemeldinger på fra andre, og vi arbeider med noen større oppgraderinger av Tavla hvor ett av hovedformålene er bedre støtte for eldre enheter og nettlesere 😄

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
