### ISSUE TITLE
White screen ipad mini ios 12.5.2

### ISSUE THREAD

**Issue by tfreyd** [entur/tavla#1018]
Hi first thanks for the very nice software to make boards, unfortunately, I created a board but when I try to open it on my old iPad mini 2 running ios 12.5.2 it only displays a white screen.  I tried several internet explorer: Safari, Opera, Chrome, Edge but still the same. 

here the link: https://tavla.entur.no/t/EXm1remyd0FDcEMrnCkM 

has such issue been reported ? 

Thanks.

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
