### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by LuckyDjuk** [entur/tavla#105]
When I've forked this repo to set up a local version of it and execute `npm install` it freezes at the following message:
The authenticity of host 'bitbucket.org (18.205.93.0)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.

I assume this is not intended. Suggestions?

**Comment by draperunner** [comment]
This is because of the optional dependency `@entur/fonts`. But since it's in the `"optionalDependencies`, npm install should still install the other dependencies.

Are you sure it freezes and not finishes? Does `npm start` work after running install?

**Comment by LuckyDjuk** [comment]
It freezes. Install was left alone until today and looks exactly the same. If I run `npm start` now it results in `sh: wp: command not found`

This is on a Mac if you're trying to figure this out.

**Comment by draperunner** [comment]
That's strange. But it looks like it might be related to bash (`sh`). Could you pull the latest changes from master and try again? Maybe this did the trick: #104 

Also, could you post the results of `bash --version` and `node --version`?

**Comment by vkasraj** [comment]
I was also frozen for me at that stage. I just hit enter and It resumes installing.

**Comment by draperunner** [comment]
I'm closing this issue as I cannot reproduce it. Please open it again if anyone has further problems with installing dependencies.
