### ISSUE TITLE
Kolumbus and Brakar bysykkel - Tone down information about "låser"

### ISSUE THREAD

**Issue by tsobuskerudbyen** [entur/tavla#1067]
For the cycle share systems to Kolumbus and Brakar, the number of docking stations "låser" is not at all as important as the solution in e.g. Oslo. This is because a rented bike must be delivered in a free dock, but if the station is full of bikes it can still be delivered close to the docking station based on GPS position  (as set by the operator). In addition to this bicycle parking location (to pick up or deliver a bike) can also be virtual. I.e. just a GPS area ([marked as red locations on the first map on this page](https://www.brakar.no/bysykkel/)).

**Improvement suggestion 1: Mark "låser" as not as important”** Can this information be added on these types of cycle share systems? E.g. that there is a small text: "Ved ingen ledige dockingstasjoner kan sykkelen leveres intill."

**Improvement suggestion 2: Virtual drop off/delivery points do not need "låser" info**: 
Tavla displays for example: 
> 2 sykler 0 låser.

There is no need to display "0 låser" here, as you can have as many bikes as you need here. (Within the space assigned that is.)

Example: https://tavla.entur.no/t/kz7KybUCpajeOVaLwgvR

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
