### ISSUE TITLE
Support for "smart mirror" mode

### ISSUE THREAD

**Issue by selbekk** [entur/tavla#107]
I'd love to have this as a part of my smart mirror. However, that requires this to be more black and white. Would it be possible to implement this?

**Comment by selbekk** [comment]
cc @draperunner

**Comment by draperunner** [comment]
In our backlog (not on GitHub) we have plans for making Tavla much more customizable with the possibility of selecting different _themes_ and creating your own. When will this be implemented? Hard to say.

**Comment by selbekk** [comment]
In #hacktober, perhaps? ;-)

**Comment by draperunner** [comment]
Closing this in favor of https://github.com/entur/tavla/issues/142 which relates to customization of colors. :)
