### ISSUE TITLE
No info about Sparkesykkel in Drammen

### ISSUE THREAD

**Issue by tsobuskerudbyen** [entur/tavla#1083]
Trying to show an overview around "Bragernes torg" in Drammen. We have multiple providers in the city (we have even made our own basic map of it fra Entur's data, see here - just ignore the icon - https://leonard.io/gbfs-map/?system=boltdrammen ).

Why isn't the this data visible in e.g: https://tavla.entur.no/admin/1n7Bt6ckwnOVQdvARYm6 ?
![bilde](https://github.com/entur/tavla/assets/70061303/a5d065d2-896b-4670-b476-5b83c4cca841)

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
