### ISSUE TITLE
Initialize TypeScript

### ISSUE THREAD

**Issue by draperunner** [entur/tavla#109]
Let's go for TypeScript in this project. If you'd like to help us out, that's cool. 

It's not necessary to fully type the whole project to close this issue, only set up the initial configuration and build step (compilation). Maybe convert one file for testing.

This PR should be good inspiration: https://github.com/draperunner/kramster/pull/14

**Comment by srkyaganti** [comment]
Hi, Can I pick this up?

**Comment by draperunner** [comment]
You can pick it up!

**Comment by draperunner** [comment]
Closed by #111
