### ISSUE TITLE
Responsive? phones?

### ISSUE THREAD

**Issue by Dabendorf** [entur/tavla#1096]
Hey,
Is it just me or is the responsive option not really that responsive? I build a board and tried to open it on a usual, new iPhone and neither "responsive" or any of the others are fully visible on it ![image](https://github.com/entur/tavla/assets/9696353/4bdd1d18-f191-4ce5-8f79-7404c0848a81)

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
