### ISSUE TITLE
Kolliderende bokser med rutenavn i "Tidslinje"-visning

### ISSUE THREAD

**Issue by SimenHolmestad** [entur/tavla#1103]
Hvis man har en tavle med "Tidslinje"-visning og det kommer to avganger veldig tett vil tekstene til disse overlappe. Se for eksempel de to bussene til venstre i bildet under:

<img width="565" alt="Screenshot 2023-07-01 at 19 10 23" src="https://github.com/entur/tavla/assets/30159942/c6daec5f-7130-469f-b46b-90b22e1abe3b">

Her er det ikke mulig å se hva slags rute den ene avgangen har.

Er det mulig å ordne dette på et vis? For eksempel ved å flytte boksene over hverandre? (men fortsatt pilen rett over riktig buss/trikk slik at man kan se hvilken boks som hører til hvilket ikon?)

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
