### ISSUE TITLE
Lagre endringer-pop-up

### ISSUE THREAD

**Issue by forteller** [entur/tavla#115]
Når man gjør en endring og trykker på pilen for å gå tilbake til tavla blir du spurt om du vil gå tilbake uten å lagre endringene:

![Screenshot from 2019-10-30 11-46-01](https://user-images.githubusercontent.com/343561/67851607-18c0a080-fb0b-11e9-8b82-26332b8a5567.png)

Men det er ingen knapp for å lagre endringene, og selv om du velger ja så blir faktisk endringene lagret. 

Enten må det være en "Lagre endringer"-knapp og tilbake-knappen må ikke lagre endringene (eller fjernes til fordel for en annen "Avbryt"-knapp), eller så må denne pop-upen fjernes.

**Comment by draperunner** [comment]
Hei!

Det er ein "Oppdater tavla"-knapp nede til høgre på admin-sida. Er den kanskje for vanskeleg å finne?

At det ser ut som at endringane faktisk blir lagra ved OK var ein bug. Eg har fiksa denne no. Saken var at endringane ikkje vart _persistert_, altså om du refresha sida så ville du få dei gamle innstillingane tilbake.

**Comment by forteller** [comment]
Ah, ja, den knappen la jeg ikke merke til. Legg den nederst til venstre isteden, kanskje?

**Comment by forteller** [comment]
Siden det nå står i popupen hvor lagre-knappen er, så må vel det være greit nok :) Takk!
