### ISSUE TITLE
Fjern hele "Stoppesteder"-konlonnen når man fjerner stoppesteder

### ISSUE THREAD

**Issue by forteller** [entur/tavla#116]
I innstillingen, når man slår av Bysykkel blir hele kolonnen for bysykler fjernet, slik man vil anta.

Når man slår av Buss, T-bane og/eller Trikk blir kun boksen borte, ikke overskriften og søkeboksen.

![Screenshot from 2019-10-30 11-52-53](https://user-images.githubusercontent.com/343561/67852379-989b3a80-fb0c-11e9-9cae-db09f96c1c09.png)

**Comment by draperunner** [comment]
Hei! Eg trur ikkje me kan fjerne søkefeltet sjølv om man slår av transportmidla, fordi dei transportmidla du ser i lista er basert på det som er tilgjengeleg innanfor gitt radius. Sjå for deg at du vil også søke opp eit stopp som er utanfor radiusen din som har andre middel, f.eks. ei ferjekai i Nordland. Det må framleis vere mogleg. Eigentleg trur eg me ikkje bør fjerne boksen heller.

**Comment by draperunner** [comment]
Eg har no lagt ut ei endring som gjer at ikkje boksen forsvinn sjølv om du slår av transportmidla.
