### ISSUE TITLE
Tas ikke høyde for at locality mangler i stoppestedssøk

### ISSUE THREAD

**Issue by seanes** [entur/tavla#117]
Søk på stoppested med resultater fra ikke-norske adresser, viser `<Navn>, undefined`.
Mappingen i `fetchSuggestions ` tar ikke høyde for at `locality` fra `Pelias` kan være `undefined` (som er i tilfelle for svenske adresser): 
https://github.com/entur/tavla/blob/9b1fda987adc4884942059662e3a509ed6682f25/src/containers/Admin/StopPlaceSearch/index.tsx#L28

Kanskje dette burde løses i SDK-et?

**Comment by draperunner** [comment]
Takk, Sean! Eg kan legge til ein kjapp for om locality er definert.

**Comment by draperunner** [comment]
Fixed!
