### ISSUE TITLE
Flytte bokser med drag-n-drop

### ISSUE THREAD

**Issue by forteller** [entur/tavla#123]
La oss si at jeg legger til tre stoppesteder og bruker tid på å velge ut nøyaktig de avgangene jeg ønsker å vise på hver av dem, bare for å komme på at jeg burde hatt holdeplassene i en annen rekkefølge. Da hadde det vært veldig fint å kunne dra og slippe dem dit de passer, framfor å måtte slå av (kan ikke slette) noen av dem og legge dem til på nytt i ønsket rekkefølge og så endra på avgangene på hver av dem igjen.

I tillegg hender det noen ganger at enkelte bokser blir veldig små. Da hadde det vært fint om man kunne valgt at en annen bok skal ligge under den, om man ønsker. Eksempel fra en annen issue her på Github:

![Screenshot](https://user-images.githubusercontent.com/1040614/60679240-35173e00-9e87-11e9-88e1-faa339610ef4.jpg)

Her hadde det vært fint om man kunne valgt å dra Oslo S under eller over Haugerud, om det er slik det passer best å organisere tavla si for å passe på den skjermen man skal bruke det på.

I samme bane hadde det vært veldig fint om selve klokka også var en boks man kunne velge å dra dit man vil ha den, slik at man kan legge den over eller under en annen boks som er liten, og på den måten få klokkeslettet større, og der man ønsker det. Men det er kanskje et annet ønske til en annen issue :)

**Comment by draperunner** [comment]
Hei! Takk for innspelet. Me har tenkt på dette sjølv, men det er ein del situasjonar som må tenkast gjennom, samt at det er ganske avansert i seg sjølv. F.eks. må me ha ein god måte å persistere layouten slik at ved refresh og deling vil tavla sjå lik ut.

**Comment by cjrorvik** [comment]
Hei @forteller ! Da har vi prodsatt en endring der man kan flytte rundt på boksene på Tavla (_kun avganstavlene, ikke klokka_). Posisjonen på elementene blir lagret ned til localStorage, så den må da settes på nytt hvis man skulle bytte nettleser eller ønsker å dele url'en for tavla med noen andre. Vi anså dette som en enkel vei for å komme videre på, så kan vi eventuelt se på å videreutvikle denne funksjonaliteten senere :) 

Takk for feature request'en! Håper dette vil være til hjelp for deg :)

**Comment by forteller** [comment]
Fantastisk! Tusen takk! :)
