### ISSUE TITLE
MagicMirror²-modul

### ISSUE THREAD

**Issue by forteller** [entur/tavla#127]
Dette er en litt større feature request, så jeg skjønner godt om dere ikke tar det opp med det samme, men håper uansett det er noe dere kan vurdere for enten nå eller en gang i framtida.

MM² er et veldig kult FOSS system for å lage en infotavle til eget hjem. De har [ørten moduler](https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules) med alle mulige funksjoner, og jeg tenkte det kunne vært veldig kult med en offisiell Entur-tavle-modul. Mens jeg skrev dette sjekket jeg og fant at en fyr som heterArve allerede [har laget en Entur-modul](https://github.com/Arve/MMM-Entur-tavle), men jeg syns fremdeles det hadde vært veldig fint med en offisiell modul – elller, enda bedre, at dere går inn og hjelper Arve. Da kan dere feks legge til nye funksjoner, slik som den nye tidslinje-visningen.

Bare en idé :)

**Comment by draperunner** [comment]
Hei og takk for ideen! Me har nok ikkje så god kapasitet til å lage ein offisiell MagicMirror-modul sjølve. Men dette er ein ypperlig muligheit for aktive MagicMirror-brukarar som Arve å lage kule ting med våre API og data. Så heia Arve! Kanskje du kan opprette issues der for ny funksjonalitet som likner tidslinjevisning? :)
