### ISSUE TITLE
Justere størrelsen på boksene

### ISSUE THREAD

**Issue by forteller** [entur/tavla#129]
Nå som dere har vært så fantastiske og gjort det mulig å flytte rundt på boksene (#123), så mangler det bare én ting for å gjøre den funksjonen komplett: Endre størrelse på boksene. Dere har jo gjort det mulig å plassere boksene i forskjellige høyder, men noen bokser bruker ikke hele høyden sin, og andre er man kanskje ikke interessert i mer enn de par øverste punktene i, og da hadde det vært fint å kunne putte to bokser over/under hverandre, men fremdeles ikke ta mer plass i høyden tilsammen enn én normal boks.

Mulighet til å justere størrelsen i bredden hadde også vært fint, hvis man feks vil utnytte mer av bredden på skjermen i en situasjon som denne:

![Screenshot from 2020-01-07 00-41-56](https://user-images.githubusercontent.com/343561/71857124-a067f400-30e6-11ea-95ed-4a6915c95480.png)

Tusen takk igjen! :)

**Comment by draperunner** [comment]
Hei! Du kan justere høgden ved å trykke og dra frå nedre høgre hjørne på kvar boks.

**Comment by forteller** [comment]
Næmmen! Jeg så ikke den lille fliken der i hjørnet, og testet bare nederst, ikke i hjørnet. Så supert! Men, mangler justering av bredden :)

**Comment by othlar** [comment]
Vet noen om det er mulig å definere et visningsområde for boksene, Ikke alltid mulig å dra ut visningsboksen med mus. OK på PC men mer komplisert med player SW på skjermer og fjerndrift.

**Comment by draperunner** [comment]
@othlar i løpet av sommaren er planen å implementere persistering av boksane sin plassering. Altså at man kan dra og justere boksane på sin eigen PC og at dette vil bli huska også på andre skjermar/maskiner.

**Comment by wfeiring** [comment]
Nå kan man justere i bredden i tillegg til i høyden (ref #281 ), så lukker denne. Det er ikke mulig å definere et visningsområdet @othlar, men det burde gå implementere. Hvis du fortsatt ønsker det må du gjerne åpne et nytt issue for akkurat det.
