### ISSUE TITLE
Avganger om antall minutter

### ISSUE THREAD

**Issue by trugrand** [entur/tavla#1298]
Savner muligheten til å starte visningen med avganger om antall minutter fra nå. Altså kunne vise avganger som er om minimum f. eks 8min, og ikke bare de som har avgang "nå"

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
