### ISSUE TITLE
Tøm bysykkel-søkefeltet etter bruk

### ISSUE THREAD

**Issue by forteller** [entur/tavla#130]
Når man legger til et nytt stoppested så tømmes automatisk søkefeltet så det er klart for en ny input. Dette skjer ikke med bysykkelstativ-søkefeltet. Der beholdes teksten og man må markere den for å kunne søke etter noe nytt.

Firefox 71, Ubuntu 19.10

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
