### ISSUE TITLE
Valg av stoppested med piltaster fungerer ikke

### ISSUE THREAD

**Issue by forteller** [entur/tavla#131]
**Hva**

- Skriv én bokstav i søkefeltet
- Bruk piltastene for å velge et forslag
- Trykk enter

**Forventet resultat**

Du kan velge det resultatet du vil med piltastene, og bruke så lang tid du vil på å velge uten at noe skjer. Når du trykker enter blir det valgte forslaget blir lagt til og søkeboksen tømmes, klar for nytt søk. Slik fungerer bysykkel-søkeboksen.

**Faktisk resultat**

I Stoppesteder-søkeboksen fungerer det anderledes: Hvis du slutter å trykke på piltastene et lite øyeblikk flyttes teksten du står på opp i søkeboksen, og alle de andre resultatene forsvinner fra dropdown-boksen. Isteden gjennomføres et nytt søk basert på den nye teksten som nå står i søkeboksen, og resultater basert på dette vises i dropdownen. Men det samme stedet i dropdownen er fremdeles valgt, nå med et nytt resultat. 

Hvis du så trykker enter blir det resultatet du nå står på brukt, ikke det resultatet du i første omgang valgte.

**System**

Firefox 71, Ubuntu 19.10

**Comment by draperunner** [comment]
Hei! Dette skal fungere no. Piltaster og enter kan brukast for å velge både stoppestader og bysyklar. Tekstfeltet blir ikkje tømt (#130), men det fikser me seinare.
