### ISSUE TITLE
Ikke mulig å vise tavla.entur innhold på skjermer, OK på PC

### ISSUE THREAD

**Issue by othlar** [entur/tavla#132]
Jeg opplever problemer med å vise innhold fra tavla.entur.no  på Samsung og Philips skjermer,
Det kommer også spørsmål om men er i Gokk  - selv om URL linken funger fint på en Win PC og nyere mobil.  Det kan se ut som om www.tavla.entur.no  er OK, men så snart det kommer koordinater bak så blir det trøbbel.  Philips skjermene kjører på Android 4.4.4 med siste FW og kan vise.  Har brukt forskjellige Signage player SW og det er samme problem med alle.  Skjermene kan vise innhold fra Entur med innebygget browser, men så snart man går via en signage app så vises det ikke.  
Andre URL linker og web sider fungerer fint. 
Jeg har vært i kontakt med flere signage leverandører og de bekrefte også samme problem.   Jeg er blitt tipset om dere bør inkludere _react-app-polyfill_ .. uten at jeg vet hva det betyr.  vellegger linker:  

 https://create-react-app.dev/docs/supported-browsers-features
https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md

**Comment by draperunner** [comment]
Hei! Takk for rapport. Me skal undersøke dette.

Akkurat kva meiner du med at du ikkje kan sjå _innhold_? Er skjermen fullstendig kvit? Eller ser du deler av sida (logo, blå bakgrunn, osv.)? Har du mulighet for å legge ved eit bilde?

**Comment by othlar** [comment]
Hei.

Ja jeg har noen bilder:
[cid:image001.png@01D5D77A.BF1A9530]
Dette viser en Hogia nettside (svart/tabell) og EnTur under – som Hvit eller Svart – på skjerm.
Det gjelder også om Entur har hele skjermen.
http://mrfylke.pubtrans.com/HWD_mr/monitor.aspx?InfoName=Moa_trafikkterminal

og https://tavla.en-tur.no/dashboard/@62-467137,6-351479/

som brukes her.


Eks på Gokk.

[cid:image003.png@01D5D77B.26284420]
Samme URL link  - kan vises fint på PC – men har også opplevd at den ikke finner lokasjonen , selv om den er søkt opp på Tavle.entur.no –

Her er et eksempel på en delt løsning med Hogia og Entur på samme skjerm som virker. (RaspberryPi3 med Otrum Signage SW.   Kan man utnytte Entur området bedre?

[cid:image002.png@01D5D77B.7ECC5FD0]



Jeg har testet med
Appspace
OtrumSignage
Xibo
Loop24Signage
Databeat

Og alle disse playerne /SW slite med å vise innhold, altså tidtabeller fra Entur.


Flott om vi får løst dette og jeg bidrar gjerne med å teste løsninger.


Kan man velge en annen bakgrunn enn BLÅ  - som blir så synlig om natten for de som står ute?
[cid:image005.png@01D5D77C.29683770]






Fra: Mats Byrkjeland <notifications@github.com>
Sendt: torsdag 30. januar 2020 12:43
Til: entur/tavla <tavla@noreply.github.com>
Kopi: Lars Øther (Serit) <lars.other@more.serit.no>; Author <author@noreply.github.com>
Emne: Re: [entur/tavla] Ikke mulig å vise tavla.entur innhold på skjermer, OK på PC (#132)


Hei! Takk for rapport. Me skal undersøke dette.

Akkurat kva meiner du med at du ikkje kan sjå innhold? Er skjermen fullstendig kvit? Eller ser du deler av sida (logo, blå bakgrunn, osv.)? Har du mulighet for å legge ved eit bilde?

**Comment by JohanEntur** [comment]
Bildet kom ikke med.

**Comment by othlar** [comment]
![Entur_Gokk](https://user-images.githubusercontent.com/60467900/73671743-d9769280-46ab-11ea-9a0b-3d45d2cb767e.png)
![Hogia_Enturi bunn_Hvit](https://user-images.githubusercontent.com/60467900/73671744-da0f2900-46ab-11ea-8a57-7feb1e89cafa.png)
![Hogia-Entur OK_Rasp3](https://user-images.githubusercontent.com/60467900/73671745-da0f2900-46ab-11ea-9538-ce2164cb1579.png)

**Comment by othlar** [comment]
Eks på Gokk.

Samme URL link  - kan vises fint på PC – men har også opplevd at den ikke finner lokasjonen , selv om den er søkt opp på Tavle.entur.no –

Her er et eksempel på en delt løsning med Hogia og Entur på samme skjerm som virker. (RaspberryPi3 med Otrum Signage SW.   Kan man utnytte Entur området bedre?

**Comment by draperunner** [comment]
Hei! Skulle gjerne visst kva nettlesarar og -versjonar desse signage-løsningane bygger på, for å enklare feilsøke og sørge for at me støttar desse.

På det siste bildet ditt blir faktisk tavla vist, som viser at "Gokk" ikkje skjer alltid. Eg trur me har ein feil at den initielle lastinga kan gå galt. Prøv å refreshe om du kan, eller vent minst 30 sekund til ny data blir henta.

Angåande blåfargen: Me har ingen mogelegheiter for å endre å fargepaletten i dag, men har ønsker om å tillate dette i framtida.

**Comment by othlar** [comment]
Takk.


Jeg skal sende deg mer info senere i kveld er på ferie


Men jeg vet at Webview  er brukt på Xibo playere


SAMSUNG bruker en nettleser i Tizen OS.



PHILLIPS  MED ANDROID 4.4.4 bruker chromium i skjermen direkte.  Og virker men får ofte Gokk...


Prøvde noen linker fra telefonen (Android)  og fikk også feil eller hvit side.


Fikk et tips som jeg la inn pæ github fra utviklere hos Xibo.




.






---- Mats Byrkjeland skrev ----


Hei! Skulle gjerne visst kva nettlesarar og -versjonar desse signage-løsningane bygger på, for å enklare feilsøke og sørge for at me støttar desse.

På det siste bildet ditt blir faktisk tavla vist, som viser at "Gokk" ikkje skjer alltid. Eg trur me har ein feil at den initielle lastinga kan gå galt. Prøv å refreshe om du kan, eller vent minst 30 sekund til ny data blir henta.

Angåande blåfargen: Me har ingen mogelegheiter for å endre å fargepaletten i dag, men har ønsker om å tillate dette i framtida.

**Comment by othlar** [comment]
Melding fra Samsung: 
OH46F is a monitor equipped with OS Tizen 2.4 (2016) and S4 (SSSP 4.0). We can see from the example page that it has been developed with Javascript (ES6).     

According to the specifications available in this web portal:
https://developer.samsung.com/SmartTV/develop/specifications/web-engine-specifications.html
 Tizen 2.4 does not support ES6,if not for one function, I am afraid.

**Comment by draperunner** [comment]
Prøv gjerne om Tavla fungerer bedre for deg no. Me har utvida nettleserstøtta.

**Comment by othlar** [comment]
Hei, takk for info. 
Samme problem, med at sidene ikke kan vises på mine playere/skjermer   ( virker ikke på en IPad3 med nogen lunde oppdatert FW)

**Comment by midnightwonder** [comment]
Dette problemet har vi hatt på Scalasystemet også. Ble løst ved at de oppdaterte til nyere nettleser

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
