### ISSUE TITLE
Mulig å benytte kun hovedinnholdet som en iframe

### ISSUE THREAD

**Issue by Chr1stian** [entur/tavla#1355]
Hadde vært gull å kunne få en https://www.w3schools.com/tags/tag_iframe.ASP av bare hovedinnholdet, altså avgangene man er interessert i.

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.

**Comment by Chr1stian** [comment]
It is related to the new version of Tavla as well, where should those issues be created @lindtvedtsebastian ?
