### ISSUE TITLE
"Nå"-duplikater på avganger

### ISSUE THREAD

**Issue by SindreKjelsrud** [entur/tavla#1385]
En god del duplikater av "Nå" ved flere stopp. Under er skjembilde av buggen.

![Screenshot from 2024-02-06 16-02-13](https://github.com/entur/tavla/assets/93219711/50b7334b-4dd3-4cc2-83e3-5daa1e1ecb5a)

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
