### ISSUE TITLE
Suggestions to features -  new "Tavla"

### ISSUE THREAD

**Issue by wiljar14** [entur/tavla#1403]
Hi,

We are currently testing the new "Tavla" and it looks great. I have some suggestions that might be beneficial for us and other end-users.
Since this is a beta, some of this might already be in your backlog waiting to be deployed.

- Combine different bus stops/connections into one box/row. E.g. Gyldenpris in Vestland has several bus stops in the same area which forces us to add them as a unique departure. When we add four different bus stops only 4 departures show at once, so ideally we would like to have two rows considering our 55 inch screens are landscape mounted.

- Option to offset by a few minutes so the board doesnt show busses that are deparing the same minute.

Regards,
William

**Comment by oyvindgrutle** [comment]
Thank you for the suggestions, it's on the block!

**Comment by espieler** [comment]
Offset departure is important to add. One of the bustops close to the office is still a 7 minute walk away. By offsetting for this, it makes more sense for the traveller. However, a different busstop is really close to the office (serves a whole different set of busses), so for that there is no need to offset.

To conclude, different stops on the same board, need individual offsets.
