### ISSUE TITLE
Tidslinja viser avgang selv om den er valgt bort

### ISSUE THREAD

**Issue by yngvar** [entur/tavla#145]
1. På t-bane-stopp Ryen har jeg valgt bort retning 4 Bergkrystallen 
![image](https://user-images.githubusercontent.com/50703/79717139-057fd800-82d9-11ea-8512-2deac9c1efd9.png)

2. På tidslinja vises likevel en avgang retning 4 Bergkrystallen
![image](https://user-images.githubusercontent.com/50703/79717177-1d575c00-82d9-11ea-9a6d-e2ae64d41903.png)

**Comment by draperunner** [comment]
Takk for rapport, det må me få sett på. Kunne du tenke deg å dele URLen til den tavla her, om du har den tilgjengeleg fortsatt?

**Comment by yngvar** [comment]
https://tavla.entur.no/dashboard/@59-8893229962854,10-811585950416351/v1::N4IgFglgJlCmB2BlALgQ2RA9vAziAXANoC6ANONHEspgA55EgByiASvinQAoA2qAxrHwBWAJzCAHCHIt2nWrwFCxwgIzTmbDjQV9BI8QDYNs7dz3LRq9WQowErTAFdksBqFPzF+yQCYALFKM-gAEAEKwAE4A5gDWkQCeOGg8PAga-kwhABKwPDgAZgmRIQAqGr4AzCGIEAC2CDgARpEAp67wGgDsAAw1sU6pUU5QZRpqwv0QIcmoOABW2CC2njreltYEhCCZOXmFxWPkvVkAUlHwTajwsDQxt919TOhY8Kg8yGCw6JEPx32IAZDSIjMYrLReCwGVTCLYgXr9QZpEGjcrEAC+5CgEFm8EEBFUPSJ5Eg9ngAFlMHAGCRyDcAO4oF7YGm2BnyVlYuZgJqYVCRKAEEClep5CA3EDooA

**Comment by draperunner** [comment]
Når eg ser nærmare på bildet ditt så er det ein linje 1 Bergkrystallen du har der. Ikkje 4. Kan det vere så enkelt?

**Comment by yngvar** [comment]
🙄😳
