### ISSUE TITLE
Feil tittel på kopier lenke/tavle

### ISSUE THREAD

**Issue by Laroha** [entur/tavla#1528]
I redigermenyen på tavlene er det en knapp for kopier tavle, men denne kopierer ikke tavlen, den kopierer link til tavlen.

Navn bør endres til Kopier link (likt som på oversikten) eller Kopier link til tavlen.

Ville også vært fint med en funksjon for kopier/dupliser tavlen for å kunne ta et utgangspunkt til ny versjon.

**Comment by emilielr** [comment]
Hei! Takk for innspill. Vi har endret slik at knappen nå heter "Kopier lenke". Vi vil se videre på funksjonen for å duplisere tavlen :)

**Comment by emilielr** [comment]
@Laroha Vi har nå fått inn en funksjon som dupliserer hele tavlen :)
