### ISSUE TITLE
Overflow Error in Live Schedule Display

### ISSUE THREAD

**Issue by rgunindi** [entur/tavla#1592]
Description:
Hi @emilielr,  I encountered an overflow error in the schedule display on our live dashboard at https://tavla.entur.no/boards. This error affects the layout and visibility of the schedule items, causing them to overflow beyond the intended container.

Steps to Reproduce:
 - Go to https://tavla.entur.no/boards.
 - Observe the schedule display on the main page. ex> https://tavla.entur.no/5koBtmqeV0eV9uzWi3Sq

Problem:
The schedule items are overflowing beyond their container, leading to a layout issue. Here is a screenshot of the overflow problem:

Overflow Problem:
![image](https://github.com/user-attachments/assets/84456d5e-9a42-4003-a8ea-94e186e73778)

Solution:
To fix this issue, I applied a CSS change that ensures the schedule items are contained within their designated area. The specific changes we made are as follows:

Here is a screenshot showing the corrected layout after applying the fix:
![image](https://github.com/user-attachments/assets/683ad340-8eb6-471e-adf3-8fc132c8936a)

I would appreciate your feedback on the approach I took to resolve this issue. If it is positive, I want to make changes and open pr.

**Comment by purusott** [comment]
Hi, 
Thank you for your submission. The development team is currently on holiday and will be returning next week. We will review and address this issue and pull request upon their return 😄

**Comment by rgunindi** [comment]
Hi @purusott ,

Thank you for the update! I appreciate the information. I'll look forward to hearing from the development team next week. Have a great holiday! :))
