### ISSUE TITLE
Tavla blir ikke oppdatert hele tiden

### ISSUE THREAD

**Issue by Dabendorf** [entur/tavla#1650]
Hei,
Jeg har til nå brukt Skyss sitt avgangstavla på mobilen min, for å se når neste buss går forskjellige steder. Dette funker ganske greit, både når man har en åpen tab på mobilen og når man installerer den på Home app.

Men dessverre opplever jeg at dette ikke funker like bra med Tavla. Tavla oppdaterer klokkeslett oppe til høyre hele tiden, men ofte forblir resten av Tavla det samme, helt til jeg refresher siden

To eksempler finnes her som vedlegg. Se på klokkeslettet og hvilken tid bussene har

Er dette noe som kan fikses? 
![photo_2024-09-15_13-08-49](https://github.com/user-attachments/assets/bb037e57-1bb4-4db2-9659-42ea06839914)
![photo_2024-09-15_13-08-50](https://github.com/user-attachments/assets/b58fbaaa-10fa-4de5-9eee-baed74178ad5)

**Comment by SelmaBergstrand** [comment]
Hei, @Dabendorf! Tusen takk for tilbakemeldingen din, den bugen har vi ikke oppdaget før!

Vi mistenker at dette kan ha å gjøre med om man har fanen med tavla åpen eller ikke, altså at dersom man er i en annen fane slutter tavla å oppdatere seg. Kunne du sjekket om det er tilfellet for deg? Dvs: hvis du åpner tavla, bytter til en annen fane noen minutter, og deretter bytter tilbake, er tavla utdatert da?

Hilsen Selma på Team Tavla

**Comment by Dabendorf** [comment]
Hei Selma! Det virker som om du har rett! Det funker fint om man er i fanen hele tiden. Det som mangles altså er sikkert en eller annen mekanisme som sjekker om man reentrer en tab. Min hovedusecase for Tavla er jo at jeg har en Homescreenapp innstallert på iPhonen min og når jeg drar fra jobb eller til byen så åpner jeg den av og til for å sjekke. Men da er det teit om jeg må restarte nettsiden hver gang jeg åpner den.

Kanskje kan dette jo fikses? :)

**Comment by SelmaBergstrand** [comment]
Enig i at dette nok kan fikses! Vi har funnet en mulig løsning der tavle-dataen oppdateres hver gang en såkalt "stale" fane åpnes på nytt. Dette er kanskje årsaken til problemet du beskriver.

Vi har nå laget dette som en PR, og får forhåpentligvis rullet ut denne endringen om ikke så lenge!

**Comment by SelmaBergstrand** [comment]
@Dabendorf Nå er problemet forhåpentligvis fikset! Takk igjen for hjelpen, og ikke nøl med å si fra om noe fortsatt ikke fungerer som det skal!

**Comment by lukasscale** [comment]
Funker for meg, tusen takk!
