### ISSUE TITLE
Sandnessjøen fungerer ikke

### ISSUE THREAD

**Issue by forteller** [entur/tavla#234]
Skrev tilfeldig inn "sa" på tavla.entur.no, og første alternativ var Sandnessjøen, så jeg valgte det. Trykker "Oprrett tavle", og alt ser først normalt ut, ser ut som at den jobber med å finne fram boksene. Men så blir hele siden bare blå, og ingenting skjer om jeg beveger musa eller trykker hvor som helst. Ingen logo eller noe, kun blått. Testet noen andre steder, og de fungerte helt fint (utenom Harekas barnehage Sa, Halden, som ga meg en feilmelding med sauer, men da fungerte ihvertfall tavla, selv om den ikke hadde noen bokser å vise meg)

**Comment by pernilak** [comment]
Hvis det ikke er noen stoppested innen en radius på 500 meter fra valgt lokasjon, vil du få den sida med sauer. Da kan du gå inne på Admin panelet, og øke radiusen eller legge inn stoppesteder manuelt :). Når det kommer til Sandnessjøen, fikk jeg akkurat samme problem.

**Comment by draperunner** [comment]
Ser at det kræsjer og alt blir blått når man velger Sandnessjøen, Alstahaug. Skal undersøke. Takk for issue, @forteller!
