### ISSUE TITLE
Klarer ikke opprette tavle

### ISSUE THREAD

**Issue by cathrbak** [entur/tavla#235]
Det skjer ingenting når jeg trykker på knappen "Opprett tavle" på landing-page. Får disse feilmeldingene i konsollen: 

<img width="1163" alt="Screenshot 2020-07-24 at 10 56 44" src="https://user-images.githubusercontent.com/28292268/88375765-76cd9c00-cd9c-11ea-93b0-d311a60e8317.png">

Må jeg logge inn først kanskje? 🤔

**Comment by draperunner** [comment]
Hei!

Kva for ein URL brukar du? Kan du ekspandere `message` i feilmeldinga, så me kan sjå `referrer`?

Dersom du har brukt `tavla.en-tur.no` (med bindestrek), så har ikkje dette fungert, for kun `tavla.entur.no` var akseptert. Men eg har lagt til tavla.en-tur.no no, så det burde fungere.

**Comment by draperunner** [comment]
Lukker saken, men du får svare om du fortsatt har problem. :)
