### ISSUE TITLE
Støtte for embeding

### ISSUE THREAD

**Issue by pf-bird** [entur/tavla#290]
Hvis man prøve å embede tavla i en IFrame så møter man på en standard `Refused to display ' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Dette er forsåvidt greit men kunne det tenkes å legge til en alternativ url som støtter embeding?

**Comment by draperunner** [comment]
Hei! Me har løsna opp igjen på denne headeren no, og krever berre https. Så får me sjå korleis me kan gjere dette på best mulig måte framover.

Fortell gjerne litt om korleis du brukar Tavla så me forstår bruksområdet ditt.

**Comment by Bird-mw** [comment]
Vi bygger en monitor løsning som viser en del forskjellig innhold. Løsningen baserer seg på å chromium/puppeteer hvor vi er bare på en side som da oppdaterer seg avhengig av konfigurasjon. For å vise f.eks en webside så må vi bruke IFrames.

Bruks område for selve tavla er faktisk vårt eget kontor, da rundt 70% av staben bruker kollektivt.

**Comment by jeppmeg** [comment]
Hei,
Har det skjedd noe med dette? Forsøker å embedde tavla i en iframe, men får bare denied. Bruken er mer eller mindre som den over. Det er upraktisk hvis man bare bruke tavla alene.
mvh 
Jon

**Comment by draperunner** [comment]
@jeppmeg det skal ikkje vere noko anna begrensing i dag enn at sida di må vere på HTTPS. Køyrer du lokalt (localhost)?

**Comment by jeppmeg** [comment]
ja, prøvde lokalt. Det går ikke. Men la det ut på en ekstern sikker webserver, og da går det fint.  Løsningen er vel da å gi den lokale HTPPS eller bruke den eksterne. 
Takk,
jon
