### ISSUE TITLE
Opplasting av logo feiler

### ISSUE THREAD

**Issue by Bird-mw** [entur/tavla#291]
![image](https://user-images.githubusercontent.com/58033648/97696839-6e28e800-1aa6-11eb-9d1e-43e63358f01b.png)

Kjører i chredge

![image](https://user-images.githubusercontent.com/58033648/97697012-b0522980-1aa6-11eb-8fbb-b2d8a3ebec67.png)

body i post er ```"{"data":{"imageUid":"lA6jDjMcWySf8POvfWx8","token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImQxMGM4ZjhiMGRjN2Y1NWUyYjM1NDFmMjllNWFjMzc0M2Y3N2NjZWUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZW50dXItdGF2bGEtcHJvZCIsImF1ZCI6ImVudHVyLXRhdmxhLXByb2QiLCJhdXRoX3RpbWUiOjE2MDQwNDI2NDcsInVzZXJfaWQiOiJHUEt5YTlJd0hEYUhLZWhkRHFjdk9pa1pPU3QxIiwic3ViIjoiR1BLeWE5SXdIRGFIS2VoZERxY3ZPaWtaT1N0MSIsImlhdCI6MTYwNDA1NTExNywiZXhwIjoxNjA0MDU4NzE3LCJlbWFpbCI6Im9sZUBwYXBpcmZseS5ubyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJvbGVAcGFwaXJmbHkubm8iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.qavsYQZbNKFWgb7rDDSLCnkkWPypkyXYP_GFsVJSSxgfgCBrjK4fdFGNEOyrE6Zo02al7ahIrzel0NCoo9goZywg48A7ltDc6aDt_nsIrnAqcopELiekTTMMy5VlbqXW9kZM8WsBkACffLGGN4hnyn9umN-AllhXxX5wCH2Mf8fp4gnPEM8vThGJ7KM7LNYt63LMfpi3p-k-fhY-TOJ_o8pM-xMswiJJccsHs05UcslicZ0kw46dkAgFNZ3Zlp__vpPUGi2qxKP9F9QgNpetL8OkbC3FYtf8zroyQYb4FFkl2CYLqlgwo9GNlngp7fdE58HYLtv6ql8YWgoLGArvAg"}}"``` 
med arg[0] ="https://us-central1-entur-tavla-prod.cloudfunctions.net/getImageUploadToken"

**Comment by draperunner** [comment]
Ser ut som at eit domene mangler i CSP-headeren. Skal fikse det asap. Takk for rapport! 👍
