### ISSUE TITLE
Kollektiv-ikonene er klint inntil hverandre

### ISSUE THREAD

**Issue by forteller** [entur/tavla#294]
Syns det hadde sett mye bedre ut med litt fysisk distansering i disse korona-tider… :P 

![Screenshot from 2020-12-03 23-14-13](https://user-images.githubusercontent.com/343561/101094902-6ab0e100-35bd-11eb-9dff-b7db6dd7dc18.png)

**Comment by draperunner** [comment]
Hei!

Transportikona våre er i familie og bur saman, så dei får heldigvis lov å klemme kvarandre. Men eg skal høyre med designer om dei skal få litt meir avstand mellom seg. Ein heil meter blir det nok ikkje.
