### ISSUE TITLE
Muligheter for værmelding

### ISSUE THREAD

**Issue by SebastianHellum** [entur/tavla#295]
Ofte når man skal ut for å ta bussen kan det være greit å sjekke værmeldingen også. Kunne det vært en ide å hatt et lite værsymbol og antall grader ved siden av klokken på tavla?

**Comment by draperunner** [comment]
Hei! Me har tenkt litt på å ha ei slik værmelding i Tavla, ja. Me må få spikra designet me ønsker og så finne tid til å implementere det. Så over nyttår ein gong, kanskje.

**Comment by forteller** [comment]
Kult. Håper det blir i en manipulerbar boks.
