### ISSUE TITLE
Tavlen forsvant, Opprett tavle-knapp fungerer heller ikke på websiden

### ISSUE THREAD

**Issue by TatyanaLo** [entur/tavla#456]
Tavlen som vi hadde forsvant for et par dager siden: https://tavla.en-tur.no/t/VMRh731U3wGaKQdpsKcI

Det vises forsiden istedet der man blir bedt om å opprette en ny tavle. "Opprett tavle" knapp fungerer samtidig heller ikke. Prøvd i Firefox og Chrome - ingen reaksjon.

**Comment by Collatty** [comment]
Hei! Takk for at du sier fra. Det var en feil fra vår side, og tavlen deres skal fungere igjen nå:)
