### ISSUE TITLE
Linjer renner utenfor bokser

### ISSUE THREAD

**Issue by DanielRTRD** [entur/tavla#55]
![screen shot 2018-08-14 at 08 02 22](https://user-images.githubusercontent.com/9788214/44074327-6712ec18-9f98-11e8-901b-a9d8097e479a.png)

Her er Schweigaardsgate 39 brukt som lokasjon. Se på Linje 19, 74 og 110 på bildet over.

**Comment by draperunner** [comment]
Hei! Me er klar over dette, og skal undersøke kva som er den beste løysinga på stopp med såpass mange avgangar.

Midlertidig løysing for deg kan vere å gå i admin-panelet og filtrere bort dei avgangane som ikkje er interessante. Då vert det forhåpentlegvis plass nok til dei som er igjen.

Takk for at du melder inn dette, og håpar tavla fell i smak!

**Comment by DanielRTRD** [comment]
Nice, kjapp og enkel quickfix! Håper det blir en bedre løsning i fremtiden 👍

**Comment by kentandersen** [comment]
Fikset i #61
