### ISSUE TITLE
Bedre dashboard for oss som administrerer mange tavler

### ISSUE THREAD

**Issue by midnightwonder** [entur/tavla#587]
For oss som administrerer mange tavler på store infoskjermer er det flere utfordringer
* mulighet for å navngi hver tavle. Vi har f.eks mange forskjellige tavler i bruk på Trondheim HBT med litt forskjellig visning. i Dagens dashboard framstår de som helt like slik at det er tungvint å finne riktig og stor fare for at man gjør feil
* enklere visning av alle tavler, trenger ikke den grafikken
* mulighet for å sortere på navn etc
* mulighet for å la flere brukere jobbe med tavlene. Sårbart at det er knytta til en bruker
* mulighet for å teste ut visninger uten at det skal gå live til de eksterne skjermene som bruker den url'en
* mulighet for deaktivere/slette tavler

**Comment by caroline-odden** [comment]
Hei! Takk for mange fine innspill! 

1. Vi har allerede en mulighet for å navngi tavler. Hvis du går på "Mine tavler" så kan du trykke på navnet og endre det der. Kan være vi må gjøre dette mer synlig!
<img width="1491" alt="Screenshot 2022-01-17 at 14 45 37" src="https://user-images.githubusercontent.com/31281040/149780549-6b3fe0a1-7cb9-4d99-af74-6a9beff70587.png">
Det er også en mulighet å endre url'en også, det gjør du ved å være på tavla du ønsker å redigere, også trykke på "Rediger" i bunnmenyen og så trykker på tabben som heter "Endre lenke"
<img width="1480" alt="Screenshot 2022-01-17 at 14 49 13" src="https://user-images.githubusercontent.com/31281040/149780611-8a1f8ffe-2309-46af-8ffc-ea17e644b035.png">
2. Vi noterer oss ønsket om enklere visning av tavler!
3. Noterer oss også muligheten for å sortere tavlene!
4. Det er mulig å ha flere brukere på en tavle, det gjør du på redigeringssiden på en tavle, under fanen som heter "Deling"
<img width="1491" alt="Screenshot 2022-01-17 at 14 49 31" src="https://user-images.githubusercontent.com/31281040/149780664-1a7b36e6-ca10-40f1-aecf-bd4c8712eb96.png">
5. Ønske om preview-funksjon på en tavle noteres også ned :) 
6. Mulighet for å slette tavle finnes også. Det gjør du fra "Mine tavler"-siden, også trykker du på de tre vertikale prikkene ved siden av navnet på tavla. 
<img width="1490" alt="Screenshot 2022-01-17 at 14 49 46" src="https://user-images.githubusercontent.com/31281040/149780717-7957959c-cb05-4bd9-b866-7a320ebde368.png">

**Comment by midnightwonder** [comment]
Takk for kjapp tilbakemelding. Det med navngivelse hadde jeg ikke lagt merke til nei. Kan nok med fordel markeres bedre.
Om du ikke skjønte det utifra teksten min så jobber jeg altså med IKT i AtB. Blant tusenvis av andre IKT-oppgaver drifter jeg våre Scalaskjermer hvor Tavla er en del av det som vises der.

Tavla er en god ide, men synes det har vært litt lite fokus på hvilke behov kollektivselskapene har for sanntidsvisning på STORE skjermer.

Pkt 4. Mulig jeg ser dårlig, men her er det tydelig forskjell på Entur-tavla og AtB-tavla. Her mangler de 2 siste fanene.
![Tavla_rediger](https://user-images.githubusercontent.com/97892573/149897645-446c100b-9e13-4a7b-b099-daf666d49405.PNG)

Pkt 6. Kunne sverge på at slettevalget ikke var der i går.... hehe

**Comment by caroline-odden** [comment]
Ser ut som versjonen AtB har av tavla er litt utdatert, har satt saken over til dem angående punkt 4 :)

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
