### ISSUE TITLE
Tavla på STORE skjermer

### ISSUE THREAD

**Issue by midnightwonder** [entur/tavla#589]
Tavla er en god ide, men er lite tilpasset kollektivselskapenes behov for visning på STORE informasjonsskjermer. Det vi savner i AtB er:

* Mulighet for å velge fontstørrelse. Slik det er nå blir det veldig smått. Bildet viser vår skjerm på Trondheim S sammen med BaneNor sine skjermer. Det blir litt smått...
![20210209_152350](https://user-images.githubusercontent.com/97892573/149905023-9a7c3038-3312-4149-b2eb-c819504c2d34.jpg)

* Gjøre det mulig å utnytte skjermflata bedre. Ja, det er mulig å dra boksene nedover, men ved neste visning er det borte
* Fjerne rullefeltet
* Kunne navngi boksene med noe annet enn holdeplass
* Kunne velge enkeltholdeplasser (basert på ID) og ikke automatisk ta begge retninger. Dette er en utfordring på Hurtigbåtterminalen hvor vi har 4 kaier og ønsker kun å vise avgang fra hver enkelt kai. Delvis løst med å velge hvilken rute som vises, men det er ikke idiotsikkert.
* Hindre at menyen popper opp når skjermen er i drift uten at noen beveger musa.
* Mulighet for å slå av og på bysykler og annen moro
* Muliggjøre visning av både rutetid og sanntid ("sanntid")
* Avviksinfo. 
* Forbedringer av dashboard som nevnt i annen tråd

**Comment by caroline-odden** [comment]
Takk for tilbakemeldinger :) 

Det å velge holdeplasser, slå av og på bysykler og avviksinfo er implementert, men AtB må oppdatere sin versjon av Tavla.

Vi noterer oss de andre ønskene dere har!
