### ISSUE TITLE
Tavla krasjer på kartview med livedata

### ISSUE THREAD

**Issue by Collatty** [entur/tavla#592]
Skulle vise frem kartview med livedata i et intervju også krasjer appen:((  

![image](https://user-images.githubusercontent.com/32391231/150358595-26f73d5a-7d48-489c-81ea-e6ec343c2dfb.png)

To reproduce: Gå på en tavle, sett på kartview, skru på live-data og trykk på se tavla. Da krasjer den.

**Comment by Collatty** [comment]
Så ikke #591, tipper det er samme issuet. I så fall kan denne closes etter #591 er merget.

**Comment by kseverinsen** [comment]
Hei! #591 er nå prodsatt. Kunne du bekreftet om problemet er fikset?

**Comment by Collatty** [comment]
Det funker:) Nice!
