### ISSUE TITLE
Bruk på mobil

### ISSUE THREAD

**Issue by kapir** [entur/tavla#628]
Vi har utviklet en app for sameier og borettslag. På den gjør vi blant annet linking til andre tjenester. F.eks delebil og vaskehjelp. 
Vi har som mål å blant annet tilgjengligjøre mobilietsløsninger for beboerne. 
Jeg tester nå ut å legge inn en link til en tavle (https://tavla.entur.no/t/HeimeconsulensB). Slik at beboerne kan trykke på den i vår app og ser på den i sin mobil.

For dette bruksområdet ser jeg noen utfordringer med løsningen og tenkte dette var et fint sted å ramse dem opp. Gi lyd hvis jeg skal dele dem opp på noen måte.

1. Kartet dukker ikke opp på tavlen.
2. Ved åpning på mobil vises først bysykkel, så dukker kollektive stoppesteder opp etterpå. Her tenker jeg det hadde vært bedre med laste indikator.
3. Jeg klarer ikke å endre rekkefølge på gjenstandene slik at jeg kan optimalisere basert på hva jeg ønsker
4. Menyen som dukker opp på mobil (rediger og mine tavler) virker veldig unødvendig, kunne godt vært gjemt bak en knapp eller "swipe"
5. Kartvisningen virker egentlig som et bra alternativ men dumt at den ikke inneholder sparkesykler og sanntidsinformasjon.
6. Å kunne trykke på kartvisningen og forstå hva oransj v og sykkel betyr hadde vært bra. Gjerne linking til hvordan man benytter dem. 
7. På desktop er det bare fullt av "nå" avganger som ikke stemmer på bussholdeplassen "Strømsbrua"

**Comment by kapir** [comment]
Takk for respons, i forhold til punkt 5 mener jeg kart "visningen" der hele skjermen er kart.
Eks: https://tavla.entur.no/t/QAHeime

**Comment by kseverinsen** [comment]
Jeg lager en sak på manglende sparkesykler og sanntidsvisning i kartvisning 👍  Har nå lagt ut fiksen for punkt 1 og 7.

**Comment by kseverinsen** [comment]
Ser det er støtte for sparkesykler og sanntidsvisning i kartet, se f.eks https://tavla.entur.no/t/Iuc33oHw31QQlQiGT03S 
Sparkesykkel må bare toggles på i innstillingene, men sanntidsdata er noe operatørene må sende inn til oss. Kolumbus leverer ikke disse dataene til oss i dag, men de jobber med det.
