### ISSUE TITLE
Tavla fungerer ikke lenger som tiltenkt i Scala

### ISSUE THREAD

**Issue by midnightwonder** [entur/tavla#800]
Vi i AtB har problem med Tavla når vi bruker den i Scala. Da blir det kun en hvit skjerm. Dette ble oppdaga torsdag 3.11.22 . Har dere gjort endringer?
Nesten samme problem med "vår" tavle, men der kommer det "du er på ville veier" og så virker det litt innimellom. Entur sin tavle er nå permanent nede for oss. Dette er ganske kritisk da vi bruker dette på store informasjonsskjermer på knutepunkt for buss og båt,

Er det noe dere kan fikse?

**Comment by orhels** [comment]
>  Vi i AtB har problem med Tavla når vi bruker den i Scala.
Hva mener du med at den brukes i Scala? Har dere en url til en tavle som ikke funker?
Vi gjøre kontinuerlig forbedringer på tavla og det har vært noen større endringer den siste tiden.
