### ISSUE TITLE
Funksjon for å splitte forskjellige retninger i forskjellige kolonner

### ISSUE THREAD

**Issue by forteller** [entur/tavla#81]
Hei. Takk for en veldig kul tjeneste! Jeg har ønsket meg å lage noe sånt som det her for en skjerm jeg kan se på om morgenen, for å vite om jeg må løpe for å rekke banen eller ikke. Men jeg kan ikke kode for fem flate øre, så da jeg så denne tenkte jeg at den kanskje er en mulig løsning å bruke på en slik skjerm på en Raspberry Pi eller noe.

Men det er sjelden jeg trenger å haste avgårde for å rekke banen som går vekk fra sentrum. Så jeg lurte på om dere kan legge til en funksjon hvor man kan splitte opp baner og busser i én kolonne for hver retning (f.eks. én kolonne for "retning sentrum" og én for "vekk fra sentrum"), og også velge å vise kun den ene eller den andre eller begge kolonner.

Takk!

**Comment by draperunner** [comment]
Hei og takk for innspel! Dette er absolutt interessant. #68 handlar litt om det samme. Me får ta opp til vurdering om dette er noko me skal implementere.

**Comment by jansag** [comment]
Føyer meg til dette ønsket. Her på Bryn i Oslo går det til tider så mange busser og t-baner at man ser bare en liten del av disse. Splitte buss og bane er en nødvendighet. Å splitte i retning er kanskje ikke nødvendig, men om det lar seg gjøre så er det kun aktuelt for t-bane (fra sentrum/mot sentrum), bussene går vel alle mulige retninger.
https://tavla.en-tur.no/dashboard/@59-90846335438317,10-813505130052153/

**Comment by forteller** [comment]
Nå har jeg sjekket appen, og der kan man legge til enkelt-linjer som favoritter for å se neste avgang. Hvis man legger til feks 5 Vestli og 5 Ringen kan man se klokkeslettene for dem adskilt fra hverandre (alle avgangene på 5 Vestli ett sted og alle avgangene på 5 Ringen et annet sted), og man kan velge å legge til akkurat de linjene man selv vil, man trenger ikke å se enten alle avganger fra Hasle, både med buss og bane, eller ingen.

Dette er det jeg ønsker meg for Tavla også. Jeg forstår dere har en hacktober nå, og hvis jeg kan være så frekk å aller mest ydmykt ønske meg én ting dere bør prioritere, så ville det vært dette :D

Takk!

**Comment by draperunner** [comment]
Me har no lansert ein ny versjon av Tavla med fridom til å velje samme stoppestad fleire gonger og filtrere ulike linjer for desse. Då kan du f.eks. ha to Brynseng, ein med t-bane og ein med buss. Eller du kan ha dei som går mot sentrum i den eine, og frå sentrum i andre. 

Løyser dette problemet, @forteller @jansag?

![image](https://user-images.githubusercontent.com/4339443/66990852-44816680-f0c7-11e9-9528-791ae6d06c81.png)

![image](https://user-images.githubusercontent.com/4339443/66990812-316e9680-f0c7-11e9-939b-3ae520cf752b.png)

**Comment by forteller** [comment]
Dette virker helt perfekt, utfra de use casene jeg klarer å komme på akkurat nå!

Eller, ikke _helt_ perfekt: Ett, lite problem er at det kan bli veldig mange linjer fra én holdeplass, og du må drive å slå av nesten alle sammen av dem for hver eneste av de kolonnene du vil ha. Kunne dere lagt inn en funksjon for "slå av alle", så man bare trenger å slå på igjen de man vil vise? Hadde spart en del tid. Men ikke kritisk.

Tusen takk!

**Comment by draperunner** [comment]
Einig i at me burde forenkle utvalg under store stoppeplassar. F.eks. ved å slå av/på alle eller filtrere på transportmiddel per stopp. Men eg lukker dette issuet, sidan funksjonaliteten i alle fall finst. Takk for sjekk!
