### ISSUE TITLE
Scrollbars i Firefox

### ISSUE THREAD

**Issue by forteller** [entur/tavla#82]
I tillegg til å være en veldig bra og nyttig tjeneste, så ser den også nokså bra ut. Men hele det positive inntrykket av utseende ødelegges i stor grad av alle scrollbarene som vises i Firefox, ihvertfall hos meg.

Når jeg tester i en annen nettleser blir det ikke sånn, så jeg antar dette er en bug.

Skjermbilde fra Firefox 66.0.5 i Ubuntu 19.04, 64 bit. Håper dere kan fikse.

Takk!

![Screenshot from 2019-05-21 20-26-52](https://user-images.githubusercontent.com/343561/58121228-322dfa00-7c07-11e9-8058-be257b709e5e.png)

**Comment by draperunner** [comment]
Dette er no fiksa (8b2b1da9551780a21b3c8e29c0eb74a1978076d4).

**Comment by forteller** [comment]
Ekstremt raskt levert! Tusen takk!
