### ISSUE TITLE
Tilpass utfra skjerm/vindu-størrelse

### ISSUE THREAD

**Issue by forteller** [entur/tavla#83]
Det er ganske lang avstand mellom kolonnene. Det ser bra ut på store skjermer/i et stort vindu, men man har ikke alltid det. Jeg syns det hadde vært veldig fint om kolonnene "fløt" for å tilpasse seg størrelsen på vinduet til enhver tid, både ved å endre avstanden mellom kolonnene og størrelsen på kolonnene selv.

Enda en grunn til dette er at hvis man har et vindu som er for lite til å vise alle kolonnene i dag så er det umulig å se at det er flere kolonner du kan scrolle bort og se

Eksempel: Her er det to ekstra kolonner til venstre, men det vises ingen tegn til det, så hvis jeg ikke visste det fra før ville jeg ikke funnet dem
![Screenshot from 2019-05-22 11-18-15](https://user-images.githubusercontent.com/343561/58162906-529b9a00-7c83-11e9-86fe-6d46d819ce36.png)

**Comment by quesara** [comment]
Vi har jobbet altfor lite med å tilpasse Tavla for ulike skjermer, f.eks. visning på mobil som kan brekke ganske stygt. Jeg har lagt inn din kommentar og skjermbilde på den saken, og håper at vi snart kan ta tak i den.
Morsomt å se at Tavla blir tatt i bruk!

**Comment by forteller** [comment]
Takk skal du ha! Jeg har lyst til å bruke Tavla slik som beskrevet her: https://github.com/entur/tavla/issues/81

Men det virker tungvindt at issues folk legger inn her må flyttes over på et annet verktøy. Hva med å bare jobbe direkte her? :)

**Comment by forteller** [comment]
Jeg ser at dette er implementert nå. Veldig bra! Hadde egentlig tenkt å lukke denne, men oppdaget at det fremdeles må finnes en måte å sikre at det ikke blir uleselig/stygt når skjermen er liten, men akkurat ikke liten nok til at boksene kommer én og én under hverandre:

![Screenshot from 2020-01-07 00-27-41](https://user-images.githubusercontent.com/343561/71856642-e1f79f80-30e4-11ea-912c-e2d9a62a1e2d.png)
Jeg foreslår en minimums-størrelse på boksene som gjør at de kommer under hverandre, men fremdeles mer enn én i bredden, hvis det gir mening. Altså når de når X px brede så hopper én og én boks ned under de andre. Men usikker på om det kan være en fast bredde som trigger dette, for noen navn er veldig lange, så det må kanskje heller være basert på hvor nærme høyrekanten av boksen navnet kommer? Hvis du skjønner?

Bare et forslag.

**Comment by magnusrand** [comment]
Hei, ettersom det har vært flere designendringer som tar for seg disse problemene siden sist anser jeg dette issuet som løst for nå. Åpne gjerne opp et nytt issue hvis du fortsatt har ønsker eller finner problemer med nårværende løsning 😊
