### ISSUE TITLE
Kombinerer holdeplasser som ikke er samme

### ISSUE THREAD

**Issue by forteller** [entur/tavla#84]
På Hasle er det to holdeplasser som har samme navn, "Hasle". En bussholdeplass og en t-banestasjon. Disse ligger ikke på samme sted, selv om de har samme navn. Likevel vises de i samme kolonne. Er dette meningen? Det virker noe forvirrende, tenker jeg. Kanskje lage en innstilling hvor man kan velge?
![Screenshot from 2019-05-22 11-18-15](https://user-images.githubusercontent.com/343561/58163162-cb9af180-7c83-11e9-860f-bcc2264f138c.png)

**Comment by quesara** [comment]
Hei, takk for innspill. Vi har samme strukturering av stoppesteder i Tavla som i app og web. Meningen er at man skal slippe å forholde seg til mange stoppesteder med samme navn (det er mange nok i hele landet totalt). Dette er en struktur som også Ruter har vært med å definere, og bruker i sin app.
Vi har planer om å bygge ut tavla med info om plattform/spor, og eventuelt med mulighet for å få linjene sortert på plattform; håper at dette vil hjelpe. Jeg kan ikke love når dette blir tatt tak i, men har laget en sak på din tilbakemelding og koblet den opp til saken med plattformsinfo.

**Comment by forteller** [comment]
Nå har jeg sjekket appen, og der kan man legge til enkelt-linjer som favoritter for å se neste avgang. Hvis man legger til feks 5 Vestli og 5 Ringen kan man se klokkeslettene for dem adskilt fra hverandre (alle avgangene på 5 Vestli ett sted og alle avgangene på 5 Ringen et annet sted), og man kan velge å legge til akkurat de linjene man selv vil, man trenger ikke å se enten alle avganger fra Hasle, både med buss og bane, eller ingen.

Dette er det jeg ønsker meg for Tavla også. Jeg forstår dere har en hacktober nå, og hvis jeg kan være så frekk å aller mest ydmykt ønske meg én ting dere bør prioritere, så ville det vært dette :D 

Takk!

**Comment by draperunner** [comment]
Hei @forteller. Samme løysing som nemnd i https://github.com/entur/tavla/issues/81 kan brukast til å legge til Hasle fleire gonger og filtrere ulike transportmodusar for kvar Hasle-kolonne. Så eg lukkar denne saken.
