### ISSUE TITLE
Layout nullstilles ved refresh

### ISSUE THREAD

**Issue by sindrefs** [entur/tavla#892]
Har satt opp en tavle, og flytter elementene (stopp og vær) slik jeg vil ha det. Når jeg refresher siden hopper den tilbake til default layout. Observerer at det ligger data i localstorage som ser ut til å holde på layout-data, men dette endrer seg ikke. Feks. forblir `moved: false`. 

Link til tavle: [https://tavla.entur.no/t/AkZ5roOFja2I9wV054JW]( https://tavla.entur.no/t/AkZ5roOFja2I9wV054JW)
Chrome-versjon: 108.0.5359.98

**Comment by ydalir** [comment]
Hei, takk for heads up! Det bør være ordnet nå
