### ISSUE TITLE
Hoppende kolonner

### ISSUE THREAD

**Issue by jansag** [entur/tavla#91]
Hei

Ser at kolonnene for buss/t-bane, tog, bysykkel etc. av og til bytter plass. Enten fordi siden har blitt lastet på nytt, eller også plutselig av seg selv.

Når folk stresser ut av bygget her for å rekke transport hjem til middag, så vil de gjerne se den samme informasjonen på samme sted hver gang. De har ikke tid til å stoppe opp og finne den riktige kolonnen når det er 2 minutter til banen/bussen/toget går.

Kan må få innstillinger for rekkefølge?

Mvh Jan E.

**Comment by draperunner** [comment]
Hei! Takk for tilbakemeldinga. Eg skjønner absolutt problemet her. I første omgang kan me enkelt legge til ei alfabetisk sortering av kolonnene, så det i alle fall alltid vil vere konsekvent rekkefølge på dei.

Om me skal kunne støtte å velge sin eigen rekkefølge på kolonnene, må me nok tenke litt på først.
