### ISSUE TITLE
Blå bar på mouseover

### ISSUE THREAD

**Issue by forteller** [entur/tavla#93]
Når du har musen hvor som helst inne på sida vises det en blå boks oppå alle kolonnene nesten nederst på sida. Firefox 67.0.4, Ubuntu 19.04.

![Screenshot from 2019-07-03 01-14-12](https://user-images.githubusercontent.com/343561/60552742-5dd8ef80-9d30-11e9-938d-ed97ffe5e887.png)

**Comment by frankwaldal** [comment]
Denne skal bare vises når man hoverer den?

**Comment by draperunner** [comment]
Desse blå boksene, som egentlig er bunnen av kolonnene, skal _aldri_ visast. "Toolbaren" med tilbakepil og tannhjul har ein mørkeblå bakgrunn som blir lagt oppå kolonnene.
