### ISSUE TITLE
Grafiske glitcher i innstillingene

### ISSUE THREAD

**Issue by forteller** [entur/tavla#94]
Som dere ser på skjermbildet er det en del glitches her:
- Hvitt rundt seekbaren. Dette hvite dekker noe av skriften over. Føles også som at teksten under (1 m, 1000 m) er litt for langt under, kunne godt vært noen pixler høyere opp. Men på den annen side burde det være litt mer luft mellom baren og teksten over, hvis baren er ment å være ca der den er nå.
- Rød linje under tallet er alt for lang og har stygge piler etter seg. Både seekbar, piler og mulighet til å skrive inn tall manuelt virker litt smør på flesk. Foreslår å droppe pilene.
- Ordet "stoppested" etter den røde linja virker unødvendig. Det holder i massevis at søkeboksen sier "Søk på stoppested" og at kolonnen under heter "Stoppesteder". Jeg tror vi skjønner greia.
- Kolonnene under starter på forskjellig høyde.

Firefox 67.0.4, Ubuntu 19.04.

![Screenshot from 2019-07-03 01-15-33](https://user-images.githubusercontent.com/343561/60552983-667df580-9d31-11e9-98eb-60ae748ecb96.png)

**Comment by henry-ns** [comment]
you can designate me, I'll fix

**Comment by draperunner** [comment]
Great, @henry-ns. Tell me if you need a translation. :P

**Comment by draperunner** [comment]
Alt du nevner skal vere fiksa no. Takk for gode innspel, @forteller!

**Comment by forteller** [comment]
Flott!

Men nå er det ikke noe luft mellom overskrift og bokser:

![Screenshot from 2019-10-30 11-42-05](https://user-images.githubusercontent.com/343561/67851393-a94ab100-fb0a-11e9-8e8e-e1b2266f1fbb.png)

Firefox 70, Ubuntu 19.10
