### ISSUE TITLE
GitHub-link på framsida

### ISSUE THREAD

**Issue by draperunner** [entur/tavla#95]
Skulle gjerne hatt ein GitHub-logo pope til høgre på framsida og på admin-sida som peikar til repoet på GitHub (https://github.com/entur/tavla).

**Comment by vikre** [comment]
@draperunner Now slikt noe du tenker på? 
Forsiden: ![image](https://user-images.githubusercontent.com/1081202/66828155-a1a6dc00-ef50-11e9-9765-666e49a521b5.png)

Admin: 
![image](https://user-images.githubusercontent.com/1081202/66828199-bdaa7d80-ef50-11e9-8af3-88bca7a5cac3.png)

**Comment by draperunner** [comment]
Ja! Men no jobbar eg med større refaktorering av Admin-sida, så eg ville venta litt med å implementere dette, om det er det du vil 😊
