### ISSUE TITLE
Bedre utnyttelse av skjermen

### ISSUE THREAD

**Issue by marjacob** [entur/tavla#97]
Jeg har hatt Ruters SIS-monitor i stua i mange år og har vært veldig fornøyd med den, men nå som den er avviklet har jeg begynt å teste _Tavla_. Ganske fin løsning! Men jeg synes den sløser litt med plassen.

Følgende er et foto av den gamle løsningen på en 24" skjerm:
![ruter_sis-monitor_small](https://user-images.githubusercontent.com/1040614/60679243-38aac500-9e87-11e9-92fa-77fd22a86dd3.jpg)

Her er _Tavla_, med en ekstra kolonne i et forsøk på å fylle opp litt mer:
![entur_tavla_small](https://user-images.githubusercontent.com/1040614/60679240-35173e00-9e87-11e9-88e1-faa339610ef4.jpg)

Den gamle SIS-monitoren var også lettlest selv på litt avstand, mens teksten i _Tavla_ fremstår som bitteliten når man bruker den på denne måten, som betyr at man må gå helt bort til den for å lese.

Forslaget mitt er altså å justere _Tavla_ litt slik at plassen kan utnyttes mer effektivt :) Vurderte å slenge dette inn under #83, men jeg kom til at det her kanskje er snakk om større endringer enn som så.

**Comment by quesara** [comment]
Hei og takk for innspill! Kult å se at Tavla er i bruk og at du har forbedringsønsker!  
Jeg har laget en oppgave for å tillate noen valg for visning, i første omgang ser vi for oss å lage én eller et par alternative layouts som man kan velge mellom, slik at det passer bedre til de stoppestedene og linjene man har valgt, samt skjermformat. Er bare usikkert når vi får tid å løse oppgaven, men vi tror at dette også vil løse flere ønsker i samme slengen.

**Comment by jansag** [comment]
Hei

Vil si meg enig med marjacob.

Flere av våre brukere klager på at skriften er for liten. 

Hvis man øker skriften litt i selve tabellen og fjerner litt av vertikal padding/spacing, så tror jeg mye er gjort.

**Comment by draperunner** [comment]
Hei! Me jobbar faktisk no med nokre designoppdateringer på Tavla. I første omgang vil større tekst komme. Så @jansag, dette vil forhåpentligvis bli forbedra i nær framtid.

**Comment by draperunner** [comment]
@jansag No er Tavla oppdatert med litt større skriftstørrelse, og tidspunktene er har fått kvit farge for å bli meir tydelege. Håpar dette hjelper.

**Comment by jansag** [comment]
@draperunner Supert! Jeg vil tro at dette holder for vår del :)

**Comment by magnusrand** [comment]
Hei, ettersom det har vært flere designendringer som tar for seg disse problemene siden sist anser jeg dette issuet som løst for nå. Åpne gjerne opp et nytt issue hvis du fortsatt har ønsker eller finner problemer med nårværende løsning 😊
