### ISSUE TITLE
En visning bedre tilpasset mobil?

### ISSUE THREAD

**Issue by eklem** [entur/tavla#973]
Hva med å lage en visning for mobil hvor du viser hver holdeplass som et kort, omtrent som `kompakt` eller `kronologisk`, men at du kun viser en holdeplass. Og så kan du swipe horisontalt mellom kortene. I tillegg gjøre den litt mer til en PWA og få vekk URL-feltet og ikke la den være en fane i nettleseren men "selvstendig" webapp.

<img width="1505" alt="Screenshot 2023-03-01 at 20 08 01" src="https://user-images.githubusercontent.com/236656/222259684-2ad8eb6b-2ba1-42b1-8071-369b7b81b8ea.png">

Uansett, veldig bra opplegg!

**Comment by ydalir** [comment]
Hei! Veldig gøy å se engasjement for Tavla 😄 Fremover vil vi ha fokus på mer responsivt design, som vil gjøre Tavla mer egnet for små skjermer. Vi har fokus på å få den "statiske" visningen til å bli så bra som mulig, så vi kan ikke love noe om swiping på mobil og PWA, men vi vil ha det i bakhodet fremover 😃

**Comment by eklem** [comment]
Skjønner at swipe blir litt ekstra å implementere. Men å fjerne drag på elementene/enkelt-tavlene vil hjelpe mye på det som er kompakt og kronologisk visning.
