### ISSUE TITLE
Duplikat av avgangstider

### ISSUE THREAD

**Issue by cathrbak** [entur/tavla#98]
Veldig praktisk tjeneste! 

I min nettleser viser den noen ganger samme avgangstid flere ganger etter hverandre, slik som skjer på det vedlagte bildet med østerås-avgangene på Stortinget og Makrellbekken. Er dette en bug? 

<img width="865" alt="Screenshot 2019-07-12 at 15 45 04" src="https://user-images.githubusercontent.com/28292268/61132721-3d413000-a4bc-11e9-8925-5a240db9457e.png">

**Comment by draperunner** [comment]
Hei Cathrine!

Skjer dette ofte, og kun på visse linjer, som 2 Østerås?

Eg klarar ikkje gjenskape dette no, men mest sannsynlig har me enten mottatt feil data for t-bane 2 Østerås her, eller så gjekk det faktisk to linje 2 Østerås under ett minutt etter kvarandre.

Takk for at du melder inn! Send gjerne ei ny melding her om du oppdagar det igjen, så skal eg prøve å undersøke det.

**Comment by cathrbak** [comment]
Hei! 

Jeg har funnet ut hvorfor det skjer, da jeg oppdaget det samme i Ruter-appen. Så ja, dere mottar noen ganger "feil" data, men sånn jeg forstår det skjer dette når en bane bytter fra f.eks 3 min til 2 min. Her er det gjenskapt i ruter-appen: 
![IMG_0965](https://user-images.githubusercontent.com/28292268/63160571-6191ae80-c01e-11e9-976e-c7803f718461.jpg)

Dette er jo ikke noe stort problem, så får vel bare godta at det skjer en gang i blant!

**Comment by draperunner** [comment]
Hei igjen! Me hadde visst ein bug i baksystema relatert til dette. Denne skal vere fiksa for ei drøy veke sidan, så forhåpentlegvis er dette løyst.

Eg lukkar derfor dette issuet, men gi gjerne beskjed om du oppdagar dette igjen! Takk!
