### ISSUE TITLE
Feilmelding - tavla.entur via Appspace signage

### ISSUE THREAD

**Issue by wiljar14** [entur/tavla#993]
Vi bruker Appspace som signage-løsning på våre skjermer Samsung Tizen QM55B.
Det fungerer fint når vi viser tavla via nettleser på smartskjermen, men når vi skal sende innholdet via Appspace får vi feilmelding.

Feilmelding:
This webpage is not available
Erorrcode: -27(net::ERR_BLOCKED_BY_RESPONSE)
Unable to load the page. tavla.entur.no may be temporarily down or have moved to a new URL.

Vi har vært i kontakt med teknikere hos Appspace og de melder tilbake følgende :

"[ERROR]  [source :0]: Refused to frame 'https://tavla.entur.no/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https:".

My L3 team would like to know if you or whomever manages the site "tavla.entur.no" could add the following at the Content Security Policy on the site, that should get it to display. 

HTTP Response Header
Name: Content-Security-Policy
Value: frame-ancestors file://*filesystem:

I am attaching a screenshot of what this looks like in IIS, it might not look the same on your end, but the policy value should be."
![Content Security Policy in IIS](https://user-images.githubusercontent.com/127733100/224660345-b23563fc-be4f-4bf7-8727-1f165f466f0a.png)

Jeg vet ikke om det som beskrives løser problemet, har dere mulighet til å undersøke fra entur sin side om hva det kan være?

**Comment by lindtvedtsebastian** [comment]
This issue is linked to the old (deprecated) version of Tavla and will therefore be closed. If this matter is relevant to the new version of Tavla, please feel free to re-create the issue.
